fos_elastica:
    serializer: ~
    clients:
        default: { host: '%env(resolve:OPENSEARCH_HOST)%', port: '%env(resolve:OPENSEARCH_PORT)%' }
    indexes:
        card:
            persistence:
                driver: orm
                model: App\Core\Domain\Entity\Card
                provider: ~
                finder: ~
                listener: ~
            index_name: card_%kernel.environment%
