parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Core/Domain/Entity/'
            - '../src/Kernel.php'
    App\Shared\Infrastructure\Http\ExceptionSubscriber:
        arguments:
            $environment: '%kernel.environment%'
    App\Core\Infrastructure\Lambda\CardFetcher:
        public: true
    Aws\S3\S3Client:
        arguments:
            -   version: 'latest'
                region: '%env(resolve:AWS_BUCKET_REGION)%'
                endpoint: '%env(resolve:MINIO_URL)%'
                use_path_style_endpoint: true
                credentials: { key: '%env(resolve:MINIO_ACCESS_KEY)%', secret: '%env(resolve:MINIO_SECRET_KEY)%' }
    App\Core\Application\Service\Card\CardCollectionFinder:
        arguments:
            - '@fos_elastica.finder.card'
    App\Core\Infrastructure\Service\CardResolver:
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }
