parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Core/Domain/Entity/'
            - '../src/Kernel.php'
    App\Shared\Infrastructure\Http\ExceptionSubscriber:
        arguments:
            $environment: '%kernel.environment%'
    App\Core\Infrastructure\Lambda\CardFetcher:
        public: true
    Aws\S3\S3Client:
        arguments:
            -   version: 'latest'
                region: 'eu-central-1'
                endpoint: 'http://minio:9000'
                use_path_style_endpoint: true
                credentials: { key: 'root', secret: '1234Abcd' }
    App\Core\Application\Service\Card\CardCollectionFinder:
        arguments:
            - '@fos_elastica.finder.card'
    App\Core\Infrastructure\Service\CardResolver:
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }
